import { useEffect, useRef } from 'react';

export function ConfirmDialog({ message, onConfirm, onCancel, busy = false }: { message: string; onConfirm: () => void; onCancel: () => void; busy?: boolean }) {
  const cancelRef = useRef<HTMLButtonElement>(null);
  const dialogRef = useRef<HTMLDivElement>(null);
  useEffect(() => { cancelRef.current?.focus(); const close = (event: KeyboardEvent) => { if (event.key === 'Escape' && !busy) onCancel(); }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [busy, onCancel]);
  useEffect(() => { const trap = (event: KeyboardEvent) => { if (event.key !== 'Tab' || !dialogRef.current) return; const focusable = Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), [href], input, select, textarea, [tabindex]:not([tabindex="-1"])')); if (!focusable.length) return; const currentIndex = focusable.indexOf(document.activeElement as HTMLElement); const nextIndex = event.shiftKey ? (currentIndex <= 0 ? focusable.length - 1 : currentIndex - 1) : (currentIndex === focusable.length - 1 ? 0 : currentIndex + 1); event.preventDefault(); focusable[nextIndex].focus(); }; document.addEventListener('keydown', trap); return () => document.removeEventListener('keydown', trap); }, []);
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 px-4"><div ref={dialogRef} className="w-full max-w-md rounded-lg bg-white p-6 shadow-xl" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h2 id="confirm-title" className="text-lg font-bold">Konfirmasi</h2><p className="mt-3 text-sm text-gray-600">{message}</p><div className="mt-5 flex justify-end gap-2"><button ref={cancelRef} type="button" disabled={busy} onClick={onCancel} className="px-4 py-2 border rounded text-sm">Batal</button><button type="button" disabled={busy} onClick={onConfirm} className="px-4 py-2 bg-blue-700 text-white rounded text-sm disabled:opacity-40">{busy ? 'Memproses...' : 'Lanjutkan'}</button></div></div></div>;
}
