import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getActiveVisits, checkOutVisit } from '../api/visits.api';
import { listCompanies } from '../api/companies.api';
import { Layout } from '../components/Layout';
import { type Visit } from '../types/visit';
import { type Company } from '../types/company';
import { ErrorState, EmptyState } from '../components/AsyncState';
import { confirmAction } from '../components/ConfirmationHost';
import { useLanguage } from '../i18n/LanguageContext';
import { userFacingError } from '../api/client';
import { visitStatusLabel } from '../utils/visit-status';

export function ActiveVisitsPage() {
  const navigate = useNavigate(); const { language, t, formatDate } = useLanguage();
  const [visits, setVisits] = useState<Visit[]>([]); const [companies, setCompanies] = useState<Company[]>([]); const [search, setSearch] = useState(''); const [filterCompany, setFilterCompany] = useState<number | undefined>(); const [filterDate, setFilterDate] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [checkingOut, setCheckingOut] = useState<number | null>(null); const [error, setError] = useState('');
  useEffect(() => { void loadCompanies(); }, []); useEffect(() => { void load(); }, [search, filterCompany, filterDate, page]);
  async function loadCompanies() { try { setCompanies((await listCompanies({ active: true, limit: 100 })).data); } catch (cause) { setError(userFacingError(cause, language)); } }
  async function load() { setLoading(true); setError(''); try { const result = await getActiveVisits({ q: search || undefined, companyId: filterCompany, date: filterDate || undefined, page, limit: 20 }); setVisits(result.data); setTotal(result.pagination.total); } catch (cause) { setError(userFacingError(cause, language)); } finally { setLoading(false); } }
  async function handleCheckout(visit: Visit) { if (checkingOut !== null || !await confirmAction(`${t('inside.checkoutConfirm')}\n${t('inside.checkoutDescription')}`)) return; setCheckingOut(visit.Id); setError(''); try { await checkOutVisit(visit.Id); await load(); } catch (cause) { setError(userFacingError(cause, language)); } finally { setCheckingOut(null); } }
  const hasFilters = Boolean(search.trim() || filterCompany !== undefined || filterDate); const reset = () => { setSearch(''); setFilterCompany(undefined); setFilterDate(''); setPage(1); }; const emptyMessage = hasFilters ? t('inside.noSearchResults') : `${t('inside.emptyTitle')} ${t('inside.emptyDescription')}`;
  return <Layout><div className="inside-page"><header className="page-header-compact"><div><p className="page-eyebrow">{t('navigation.inside')}</p><h1>{t('inside.title')}</h1><p>{t('inside.description')}</p></div><span className="inside-live-indicator"><span aria-hidden="true" />{t('inside.live')}</span></header>
    <div className="inside-toolbar"><div className="visit-filter-field visit-search-field"><label htmlFor="active-search">{t('inside.search')}</label><input id="active-search" type="search" value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder={t('inside.searchPlaceholder')} /></div><div className="visit-filter-field"><label htmlFor="active-company">{t('inside.company')}</label><select id="active-company" value={filterCompany ?? ''} onChange={e => { setFilterCompany(e.target.value ? Number(e.target.value) : undefined); setPage(1); }}><option value="">{t('inside.allCompanies')}</option>{companies.map(company => <option key={company.id} value={company.id}>{company.companyName}</option>)}</select></div><div className="visit-filter-field"><label htmlFor="active-date">{t('inside.date')}</label><input id="active-date" type="date" value={filterDate} onChange={e => { setFilterDate(e.target.value); setPage(1); }} /></div>{hasFilters && <button type="button" onClick={reset} className="reset-filter-button">{t('inside.reset')}</button>}</div>
    {error ? <ErrorState message={error} onRetry={load} /> : loading ? <p className="page-loading" role="status">{t('common.loading')}</p> : <><p className="result-count visits-result-count">{total} {total === 1 ? t('inside.activeVisit') : t('inside.activeVisits')}</p>{!visits.length ? <div className="visitor-empty"><EmptyState message={emptyMessage} />{hasFilters && <button type="button" onClick={reset} className="reset-filter-button">{t('inside.reset')}</button>}</div> : <div className="inside-list">{visits.map(visit => <article key={visit.Id} className="inside-card"><div className="inside-card-main"><div className="inside-card-heading"><div><p className="inside-count">{visit.VisitorCount ?? '—'} {t('inside.people')}</p><p className="inside-company">{visit.CompanyName}</p><p className="inside-host">{t('inside.host')}: {visit.HostName}</p></div><span className="status-badge bg-blue-100 text-blue-700">{visitStatusLabel('IN', language)}</span></div><dl className="inside-meta"><div><dt>{t('inside.checkIn')}</dt><dd>{visit.CheckInTime ? formatDate(visit.CheckInTime, language, { hour: '2-digit', minute: '2-digit' }) : '—'}</dd></div><div><dt>{t('inside.visitCode')}</dt><dd>{visit.VisitCode}</dd></div><div><dt>{t('inside.purpose')}</dt><dd>{visit.Purpose || '—'}</dd></div></dl></div><div className="inside-card-actions"><button type="button" className="secondary-button" onClick={() => navigate(`/visits/${visit.Id}`)}>{t('inside.detail')}</button><button type="button" className="checkout-button" disabled={checkingOut === visit.Id} onClick={() => void handleCheckout(visit)}>{checkingOut === visit.Id ? t('common.loading') : t('inside.checkout')}</button></div></article>)}</div>}</>}</div></Layout>;
}
