import { useEffect, useState } from 'react';
import { Layout } from '../components/Layout';
import { ErrorState, EmptyState } from '../components/AsyncState';
import { listAuditLogs, type AuditLog } from '../api/audit.api';

export function AuditLogPage() {
  const [logs, setLogs] = useState<AuditLog[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [action, setAction] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [q, setQ] = useState(''); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1);
  async function load() { setLoading(true); setError(''); try { const result = await listAuditLogs({ action: action || undefined, from: from || undefined, to: to || undefined, q: q || undefined, page }); setLogs(result.data); setTotalPages(result.pagination.totalPages); } catch { setError('Gagal memuat audit log.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [page]);
  return <Layout><div className="mb-5"><p className="dashboard-kicker">Administrasi</p><h1 className="text-xl font-bold">Audit Log</h1></div>
    <div className="flex flex-wrap gap-2 mb-4"><label htmlFor="audit-search" className="sr-only">Cari audit log</label><input id="audit-search" value={q} onChange={e => setQ(e.target.value)} placeholder="Cari aksi atau detail..." className="min-w-[220px] flex-1 px-3 py-2 border rounded text-sm" /><label htmlFor="audit-action" className="sr-only">Filter aksi</label><input id="audit-action" value={action} onChange={e => setAction(e.target.value)} placeholder="Aksi" className="px-3 py-2 border rounded text-sm" /><label htmlFor="audit-from" className="sr-only">Dari tanggal</label><input id="audit-from" type="date" value={from} onChange={e => setFrom(e.target.value)} className="px-3 py-2 border rounded text-sm" /><label htmlFor="audit-to" className="sr-only">Sampai tanggal</label><input id="audit-to" type="date" value={to} onChange={e => setTo(e.target.value)} className="px-3 py-2 border rounded text-sm" /><button type="button" onClick={() => { setPage(1); void load(); }} className="px-4 py-2 bg-blue-700 text-white rounded text-sm">Filter</button></div>
    {error ? <ErrorState message={error} onRetry={load} /> : loading ? <p className="text-sm text-gray-500">Memuat...</p> : logs.length === 0 ? <EmptyState message="Belum ada audit log yang sesuai." /> : <><div className="overflow-x-auto bg-white border rounded audit-table"><table className="w-full text-sm"><thead><tr className="text-left"><th>Waktu</th><th>Pengguna</th><th>Aksi</th><th>Entitas</th><th>ID</th><th>IP</th><th>Detail</th></tr></thead><tbody>{logs.map(log => <tr key={log.Id}><td>{new Date(log.CreatedAt).toLocaleString('id-ID')}</td><td>{log.UserName || 'Sistem'}</td><td>{log.Action}</td><td>{log.EntityType}</td><td>{log.EntityId ?? '-'}</td><td>{log.IpAddress || '-'}</td><td className="max-w-xs truncate">{log.Details || '-'}</td></tr>)}</tbody></table></div><div className="mobile-record-list">{logs.map(log => <article key={log.Id} className="mobile-record-card"><div className="mobile-record-heading"><strong>{log.Action}</strong><span className="text-xs text-gray-500">{new Date(log.CreatedAt).toLocaleString('id-ID')}</span></div><dl className="mobile-record-details"><div><dt>Pengguna</dt><dd>{log.UserName || 'Sistem'}</dd></div><div><dt>Entitas</dt><dd>{log.EntityType} #{log.EntityId ?? '-'}</dd></div><div><dt>Detail</dt><dd>{log.Details || '-'}</dd></div></dl></article>)}</div><div className="flex gap-2 mt-4"><button disabled={page <= 1} onClick={() => setPage(p => p - 1)} className="px-3 py-1 border rounded disabled:opacity-40">Sebelumnya</button><span className="py-1 text-sm">Halaman {page} dari {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage(p => p + 1)} className="px-3 py-1 border rounded disabled:opacity-40">Berikutnya</button></div></>}</Layout>;
}
