import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { deleteCompany, listCompanies, updateCompanyStatus } from '../api/companies.api';
import { type Company } from '../types/company';
import { Layout } from '../components/Layout';
import { ErrorState, EmptyState } from '../components/AsyncState';
import { confirmAction } from '../components/ConfirmationHost';
import { useLanguage } from '../i18n/LanguageContext';
import { userFacingError } from '../api/client';

function CompanyStatus({ active, label }: { active: boolean; label: string }) {
  return <span className={`status-badge ${active ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'}`}>{label}</span>;
}

export function CompaniesPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const { language, t } = useLanguage();
  const [companies, setCompanies] = useState<Company[]>([]); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [actionLoading, setActionLoading] = useState<number | null>(null);
  useEffect(() => { void load(); }, [search, page]);
  async function load() { setLoading(true); setError(''); try { const result = await listCompanies({ q: search || undefined, page, limit: 20 }); setCompanies(result.data); setTotal(result.pagination.total); } catch (cause) { setError(userFacingError(cause, language)); } finally { setLoading(false); } }
  async function handleToggleStatus(company: Company) { if (actionLoading !== null) return; setActionLoading(company.id); setError(''); try { await updateCompanyStatus(company.id, !company.isActive); await load(); } catch (cause) { setError(userFacingError(cause, language)); } finally { setActionLoading(null); } }
  async function handleDelete(company: Company) { if (!await confirmAction(`${t('common.delete')} "${company.companyName}"?\nSemua pengunjung, kunjungan, dan riwayat induction perusahaan ini akan ikut terhapus permanen.`)) return; setActionLoading(company.id); setError(''); try { await deleteCompany(company.id); await load(); } catch (cause) { setError(userFacingError(cause, language)); } finally { setActionLoading(null); } }
  const countLabel = total === 1 ? t('companies.companyCount') : t('companies.companiesCount');
  const emptyMessage = search.trim() ? `${t('companies.noSearchResults')} "${search.trim()}".` : t('companies.noCompanies');
  return <Layout><div className="companies-page">
    <header className="page-header-compact"><div><p className="page-eyebrow">{t('navigation.administration')}</p><h1>{language === 'id' ? 'Perusahaan yang sudah terdaftar' : t('companies.title')}</h1><p>{t('companies.description')}</p></div><button type="button" onClick={() => navigate('/companies/new')} className="primary-button">+ {t('companies.add')}</button></header>
    <div className="companies-toolbar"><div className="companies-search-wrap"><label htmlFor="companies-search">{t('companies.search')}</label><input id="companies-search" type="search" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder={t('companies.searchPlaceholder')} /></div>{!loading && !error && <span className="result-count">{total} {countLabel}</span>}</div>
    {error ? <ErrorState message={error} onRetry={load} /> : loading ? <p className="page-loading">{t('common.loading')}</p> : companies.length === 0 ? <div className="company-empty"><EmptyState message={emptyMessage} />{!search.trim() && <><p>{t('companies.emptyHint')}</p><button type="button" onClick={() => navigate('/companies/new')} className="primary-button">+ {t('companies.add')}</button></>}</div> : <>
       <div className="companies-table-wrap"><table className="companies-table"><colgroup><col /><col className="companies-status-col" />{(user?.role === 'ADMIN' || user?.role === 'SECURITY') && <col className="companies-action-col" />}</colgroup><thead><tr><th>{t('companies.company')}</th><th>{t('companies.status')}</th>{(user?.role === 'ADMIN' || user?.role === 'SECURITY') && <th className="text-right">{t('companies.action')}</th>}</tr></thead><tbody>{companies.map(company => <tr key={company.id}><td>{(user?.role === 'ADMIN' || user?.role === 'SECURITY') ? <button type="button" onClick={() => navigate(`/companies/${company.id}/edit`)} className="company-name-link">{company.companyName}</button> : <span className="company-name">{company.companyName}</span>}</td><td><CompanyStatus active={company.isActive} label={company.isActive ? t('companies.active') : t('companies.inactive')} /></td>{(user?.role === 'ADMIN' || user?.role === 'SECURITY') && <td className="text-right"><button type="button" className="row-action" onClick={() => navigate(`/companies/${company.id}/edit`)}>{t('common.edit')}</button><button type="button" disabled={actionLoading !== null} onClick={() => void handleToggleStatus(company)} className="row-action">{actionLoading === company.id ? t('common.update') : company.isActive ? t('common.deactivate') : t('common.activate')}</button><button type="button" className="danger-button" disabled={actionLoading !== null} onClick={() => void handleDelete(company)}>{t('common.delete')}</button></td>}</tr>)}</tbody></table></div>
       <div className="mobile-record-list companies-mobile-list">{companies.map(company => <article key={company.id} className="mobile-record-card"><div className="mobile-record-heading"><div>{(user?.role === 'ADMIN' || user?.role === 'SECURITY') ? <button type="button" onClick={() => navigate(`/companies/${company.id}/edit`)} className="company-name-link">{company.companyName}</button> : <strong>{company.companyName}</strong>}</div><CompanyStatus active={company.isActive} label={company.isActive ? t('companies.active') : t('companies.inactive')} /></div>{(user?.role === 'ADMIN' || user?.role === 'SECURITY') && <div className="mobile-record-actions"><button type="button" className="row-action" onClick={() => navigate(`/companies/${company.id}/edit`)}>{t('common.edit')}</button><button type="button" disabled={actionLoading !== null} onClick={() => void handleToggleStatus(company)} className="row-action">{actionLoading === company.id ? t('common.update') : company.isActive ? t('common.deactivate') : t('common.activate')}</button><button type="button" className="danger-button" disabled={actionLoading !== null} onClick={() => void handleDelete(company)}>{t('common.delete')}</button></div>}</article>)}</div>
      {total > 20 && <div className="pagination-row"><button type="button" disabled={page <= 1} onClick={() => setPage(value => value - 1)}>{t('common.previous')}</button><span>{page}</span><button type="button" disabled={page * 20 >= total} onClick={() => setPage(value => value + 1)}>{t('common.next')}</button></div>}
    </>}
  </div></Layout>;
}
