import { useEffect, useState } from 'react';
import { Layout } from '../components/Layout';
import { ErrorState, EmptyState } from '../components/AsyncState';
import { listCompanies } from '../api/companies.api';
import { getVisitReport, getVisitorReport, getInductionReport } from '../api/reports.api';
import type { Company } from '../types/company';
import { useLanguage } from '../i18n/LanguageContext';
import { userFacingError } from '../api/client';
import { createWorkbook, downloadWorkbook, reportRows, reportHeaders, safeFilename, toExcelCsv, type ExportFilters, type ExportLabels, type ReportTab } from '../utils/report-export';

type Tab = 'visits' | 'visitors' | 'inductions';
const csvHeaders: Record<Tab, string[]> = { visits: ['Kode Kunjungan', 'Tanggal', 'Pengunjung', 'Perusahaan', 'Host', 'Check-in', 'Check-out', 'Status'], visitors: ['Pengunjung', 'Perusahaan', 'Jumlah Kunjungan', 'Kunjungan Terakhir', 'Status'], inductions: ['Pengunjung', 'Perusahaan', 'Versi', 'Selesai', 'Berlaku Sampai', 'Status'] };

export function ReportsPage() {
  const { language } = useLanguage();
  const [tab, setTab] = useState<Tab>('visits'); const [companies, setCompanies] = useState<Company[]>([]); const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [loading, setLoading] = useState(false); const [exporting, setExporting] = useState(false); const [error, setError] = useState(''); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [companyId, setCompanyId] = useState(''); const [host, setHost] = useState(''); const [status, setStatus] = useState('');
  useEffect(() => { listCompanies({ active: true, limit: 100 }).then(result => setCompanies(result.data)).catch(() => undefined); }, []);
  async function load() { setLoading(true); setError(''); try { const params = { from: from || undefined, to: to || undefined, companyId: companyId ? Number(companyId) : undefined, host: host || undefined, status: status || undefined, page }; const result = tab === 'visits' ? await getVisitReport(params) : tab === 'visitors' ? await getVisitorReport(params) : await getInductionReport(params); setRows(result.data as Record<string, unknown>[]); setTotalPages(result.pagination?.totalPages ?? 1); } catch (cause) { setError(userFacingError(cause, language)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [tab, page]);
  function switchTab(next: Tab) { setTab(next); setPage(1); setRows([]); }
  const labels: ExportLabels = language === 'id' ? { reportTitle: 'LAPORAN OPERASIONAL VISITORBMC', sheetName: tab === 'visits' ? 'Kunjungan' : tab === 'visitors' ? 'Pengunjung' : 'Safety Induction', period: 'Periode', allDates: 'Semua tanggal', company: 'Perusahaan', allCompanies: 'Semua perusahaan', host: 'Host', allHosts: 'Semua host', status: 'Status', allStatuses: 'Semua status', exported: 'Diekspor', no: 'NO.', visitCode: 'KODE KUNJUNGAN', date: 'TANGGAL', visitor: 'PENGUNJUNG', companyHeader: 'PERUSAHAAN', hostHeader: 'HOST', checkIn: 'CHECK-IN', checkOut: 'CHECK-OUT', visitsCount: 'JUMLAH KUNJUNGAN', latestVisit: 'KUNJUNGAN TERAKHIR', version: 'VERSI', completed: 'SELESAI', validUntil: 'BERLAKU SAMPAI', active: 'Aktif', inactive: 'Tidak Aktif', valid: 'Masih Berlaku', expired: 'Kedaluwarsa', statusLabels: { PENDING_INDUCTION: 'Perlu Induksi', READY_FOR_CHECKIN: 'Siap Masuk', IN: 'Di Dalam', OUT: 'Sudah Keluar', CANCELLED: 'Dibatalkan', ACTIVE: 'Aktif', INACTIVE: 'Tidak Aktif', VALID: 'Masih Berlaku', EXPIRED: 'Kedaluwarsa' } } : { reportTitle: 'VISITORBMC OPERATIONAL REPORT', sheetName: tab === 'visits' ? 'Visits' : tab === 'visitors' ? 'Visitors' : 'Safety Induction', period: 'Period', allDates: 'All dates', company: 'Company', allCompanies: 'All companies', host: 'Host', allHosts: 'All hosts', status: 'Status', allStatuses: 'All statuses', exported: 'Exported', no: 'NO.', visitCode: 'VISIT CODE', date: 'DATE', visitor: 'VISITOR', companyHeader: 'COMPANY', hostHeader: 'HOST', checkIn: 'CHECK-IN', checkOut: 'CHECK-OUT', visitsCount: 'VISITS COUNT', latestVisit: 'LATEST VISIT', version: 'VERSION', completed: 'COMPLETED', validUntil: 'VALID UNTIL', active: 'Active', inactive: 'Inactive', valid: 'Valid', expired: 'Expired', statusLabels: { PENDING_INDUCTION: 'Induction Required', READY_FOR_CHECKIN: 'Ready for Check-in', IN: 'Inside', OUT: 'Checked Out', CANCELLED: 'Cancelled', ACTIVE: 'Active', INACTIVE: 'Inactive', VALID: 'Valid', EXPIRED: 'Expired' } };
  const currentFilters: ExportFilters = { from: tab === 'visitors' ? '' : from, to: tab === 'visitors' ? '' : to, company: companies.find(company => String(company.id) === companyId)?.companyName || '', host: tab === 'visits' ? host : '', status: tab === 'visits' ? status : '' };
  async function fetchAllRows(): Promise<Record<string, unknown>[]> { const params = { from: tab === 'visitors' ? undefined : from || undefined, to: tab === 'visitors' ? undefined : to || undefined, companyId: companyId ? Number(companyId) : undefined, host: tab === 'visits' ? host || undefined : undefined, status: tab === 'visits' ? status || undefined : undefined, page: 1, limit: 100 }; if (tab === 'visitors') { const first = await getVisitorReport(params); const all = [...first.data as Record<string, unknown>[]]; for (let current = 2; current <= first.pagination.totalPages; current += 1) { const next = await getVisitorReport({ ...params, page: current }); all.push(...next.data as Record<string, unknown>[]); } return all; } const first = tab === 'visits' ? await getVisitReport(params) : await getInductionReport(params); const all = [...first.data as Record<string, unknown>[]]; for (let current = 2; current <= first.pagination.totalPages; current += 1) { const next = tab === 'visits' ? await getVisitReport({ ...params, page: current }) : await getInductionReport({ ...params, page: current }); all.push(...next.data as Record<string, unknown>[]); } return all; }
  async function exportRows(asCsv = false) { if (!rows.length || exporting) return; setExporting(true); setError(''); try { const allRows = await fetchAllRows(); const workbook = createWorkbook(tab, allRows, labels, currentFilters, language); if (asCsv) { const mapped = reportRows(tab, allRows, labels, language); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([toExcelCsv(reportHeaders(tab, labels), mapped, language)], { type: 'text/csv;charset=utf-8' })); link.download = safeFilename(tab, language).replace(/\.xlsx$/, '.csv'); link.click(); URL.revokeObjectURL(link.href); } else downloadWorkbook(workbook, safeFilename(tab, language)); } catch (cause) { setError(cause instanceof Error ? cause.message : language === 'id' ? 'Gagal mengekspor laporan Excel.' : 'Failed to export Excel report.'); } finally { setExporting(false); } }
  function formatReportDate(value: unknown, includeTime = false) {
    if (typeof value !== 'string' || !value) return '-';
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return String(value);
    const locale = language === 'id' ? 'id-ID' : 'en-GB';
    const datePart = new Intl.DateTimeFormat(locale, { day: '2-digit', month: 'short', year: 'numeric' }).format(date);
    if (!includeTime) return datePart;
    const timePart = new Intl.DateTimeFormat(locale, { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }).format(date);
    return <span className="report-date-time"><span>{datePart}</span><span>{timePart}</span></span>;
  }
  function displayValue(value: unknown, cell: number) {
    if (value == null || value === '') return '-';
    if (tab === 'visits' && (cell === 1)) return formatReportDate(value);
    if (tab === 'visits' && (cell === 5 || cell === 6)) return formatReportDate(value, true);
    if (tab === 'visitors' && cell === 3) return formatReportDate(value);
    if (tab === 'inductions' && (cell === 3 || cell === 4)) return formatReportDate(value, true);
    return String(value);
  }
  const filters = <div className="report-filters"><label htmlFor="report-from">Dari tanggal</label><input id="report-from" type="date" value={from} onChange={e => setFrom(e.target.value)} /><label htmlFor="report-to">Sampai tanggal</label><input id="report-to" type="date" value={to} onChange={e => setTo(e.target.value)} /><label htmlFor="report-company">Perusahaan</label><select id="report-company" value={companyId} onChange={e => setCompanyId(e.target.value)}><option value="">Semua perusahaan</option>{companies.map(company => <option key={company.id} value={company.id}>{company.companyName}</option>)}</select>{tab === 'visits' && <><label htmlFor="report-host">Host</label><input id="report-host" value={host} onChange={e => setHost(e.target.value)} placeholder="Nama host" /><label htmlFor="report-status">Status</label><select id="report-status" value={status} onChange={e => setStatus(e.target.value)}><option value="">Semua status</option><option value="PENDING_INDUCTION">Induction diperlukan</option><option value="READY_FOR_CHECKIN">Siap check-in</option><option value="IN">Di dalam</option><option value="OUT">Sudah keluar</option></select></>}<button type="button" onClick={() => { setPage(1); void load(); }} className="bg-blue-700 text-white px-4 py-2 rounded">Terapkan</button><button type="button" disabled={!rows.length || exporting} onClick={() => void exportRows()} className="px-4 py-2 border rounded disabled:opacity-40">{exporting ? (language === 'id' ? 'Mengekspor...' : 'Exporting...') : 'Export Excel'}</button><button type="button" disabled={!rows.length || exporting} onClick={() => void exportRows(true)} className="px-4 py-2 border rounded disabled:opacity-40">CSV</button></div>;
  const values = (row: Record<string, unknown>) => tab === 'visits' ? [row.VisitCode, row.VisitDate, row.VisitorName, row.CompanyName, row.HostName, row.CheckInTime, row.CheckOutTime, row.Status] : tab === 'visitors' ? [row.VisitorName, row.CompanyName, row.VisitsCount, row.LatestVisit, row.Status] : [row.VisitorName, row.CompanyName, row.InductionVersion, row.CompletedAt, row.ValidUntil, row.Status];
  return <Layout><h1 className="text-xl font-bold mb-5">Laporan Operasional</h1><div className="report-tabs" role="tablist">{(['visits', 'visitors', 'inductions'] as Tab[]).map(item => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => switchTab(item)}>{item === 'visits' ? 'Kunjungan' : item === 'visitors' ? 'Pengunjung' : 'Safety Induction'}</button>)}</div>{filters}{error ? <ErrorState message={error} onRetry={load} /> : loading ? <p>Memuat laporan...</p> : !rows.length ? <EmptyState message="Belum ada data laporan." /> : <><div className="overflow-x-auto bg-white border rounded report-table"><table className="w-full text-sm"><thead><tr>{csvHeaders[tab].map(header => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{values(row).map((value, cell) => <td key={cell}>{displayValue(value, cell)}</td>)}</tr>)}</tbody></table></div><div className="mobile-record-list">{rows.map((row, index) => <article key={index} className="mobile-record-card"><strong>{String(values(row)[0] ?? '-')}</strong><dl className="mobile-record-details">{csvHeaders[tab].slice(1).map((header, cell) => <div key={header}><dt>{header}</dt><dd>{displayValue(values(row)[cell + 1], cell + 1)}</dd></div>)}</dl></article>)}</div><div className="flex gap-3 mt-4"><button disabled={page <= 1} onClick={() => setPage(value => value - 1)} className="px-3 py-1 border rounded disabled:opacity-40">Sebelumnya</button><span className="py-1 text-sm">Halaman {page} dari {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage(value => value + 1)} className="px-3 py-1 border rounded disabled:opacity-40">Berikutnya</button></div></>}</Layout>;
}
