import { useEffect, useState } from 'react';
import { Layout } from '../components/Layout';
import { ErrorState, EmptyState } from '../components/AsyncState';
import { listCompanies } from '../api/companies.api';
import { getVisitReport, getVisitorReport, getInductionReport, downloadCsv } from '../api/reports.api';
import type { Company } from '../types/company';
import { useLanguage } from '../i18n/LanguageContext';
import { userFacingError } from '../api/client';

type Tab = 'visits' | 'visitors' | 'inductions';
const csvHeaders: Record<Tab, string[]> = { visits: ['Kode Kunjungan', 'Tanggal', 'Pengunjung', 'Perusahaan', 'Host', 'Check-in', 'Check-out', 'Status'], visitors: ['Pengunjung', 'Perusahaan', 'Jumlah Kunjungan', 'Kunjungan Terakhir', 'Status'], inductions: ['Pengunjung', 'Perusahaan', 'Versi', 'Selesai', 'Berlaku Sampai', 'Status'] };

export function ReportsPage() {
  const { language } = useLanguage();
  const [tab, setTab] = useState<Tab>('visits'); const [companies, setCompanies] = useState<Company[]>([]); const [rows, setRows] = useState<Record<string, unknown>[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [companyId, setCompanyId] = useState(''); const [host, setHost] = useState(''); const [status, setStatus] = useState('');
  useEffect(() => { listCompanies({ active: true, limit: 100 }).then(result => setCompanies(result.data)).catch(() => undefined); }, []);
  async function load() { setLoading(true); setError(''); try { const params = { from: from || undefined, to: to || undefined, companyId: companyId ? Number(companyId) : undefined, host: host || undefined, status: status || undefined, page }; const result = tab === 'visits' ? await getVisitReport(params) : tab === 'visitors' ? await getVisitorReport(params) : await getInductionReport(params); setRows(result.data as Record<string, unknown>[]); setTotalPages(result.pagination?.totalPages ?? 1); } catch (cause) { setError(userFacingError(cause, language)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [tab, page]);
  function switchTab(next: Tab) { setTab(next); setPage(1); setRows([]); }
  function exportRows() { const mapped = rows.map(row => tab === 'visits' ? { [csvHeaders.visits[0]]: row.VisitCode, [csvHeaders.visits[1]]: row.VisitDate, [csvHeaders.visits[2]]: row.VisitorName, [csvHeaders.visits[3]]: row.CompanyName, [csvHeaders.visits[4]]: row.HostName, [csvHeaders.visits[5]]: row.CheckInTime, [csvHeaders.visits[6]]: row.CheckOutTime, [csvHeaders.visits[7]]: row.Status } : tab === 'visitors' ? { [csvHeaders.visitors[0]]: row.VisitorName, [csvHeaders.visitors[1]]: row.CompanyName, [csvHeaders.visitors[2]]: row.VisitsCount, [csvHeaders.visitors[3]]: row.LatestVisit, [csvHeaders.visitors[4]]: row.Status } : { [csvHeaders.inductions[0]]: row.VisitorName, [csvHeaders.inductions[1]]: row.CompanyName, [csvHeaders.inductions[2]]: row.InductionVersion, [csvHeaders.inductions[3]]: row.CompletedAt, [csvHeaders.inductions[4]]: row.ValidUntil, [csvHeaders.inductions[5]]: row.Status }); downloadCsv(`laporan-${tab}.csv`, mapped); }
  const filters = <div className="report-filters"><label htmlFor="report-from">Dari tanggal</label><input id="report-from" type="date" value={from} onChange={e => setFrom(e.target.value)} /><label htmlFor="report-to">Sampai tanggal</label><input id="report-to" type="date" value={to} onChange={e => setTo(e.target.value)} /><label htmlFor="report-company">Perusahaan</label><select id="report-company" value={companyId} onChange={e => setCompanyId(e.target.value)}><option value="">Semua perusahaan</option>{companies.map(company => <option key={company.id} value={company.id}>{company.companyName}</option>)}</select>{tab === 'visits' && <><label htmlFor="report-host">Host</label><input id="report-host" value={host} onChange={e => setHost(e.target.value)} placeholder="Nama host" /><label htmlFor="report-status">Status</label><select id="report-status" value={status} onChange={e => setStatus(e.target.value)}><option value="">Semua status</option><option value="PENDING_INDUCTION">Induction diperlukan</option><option value="READY_FOR_CHECKIN">Siap check-in</option><option value="IN">Di dalam</option><option value="OUT">Sudah keluar</option></select></>}<button type="button" onClick={() => { setPage(1); void load(); }} className="bg-blue-700 text-white px-4 py-2 rounded">Terapkan</button><button type="button" disabled={!rows.length} onClick={exportRows} className="px-4 py-2 border rounded disabled:opacity-40">Export CSV</button></div>;
  const values = (row: Record<string, unknown>) => tab === 'visits' ? [row.VisitCode, row.VisitDate, row.VisitorName, row.CompanyName, row.HostName, row.CheckInTime, row.CheckOutTime, row.Status] : tab === 'visitors' ? [row.VisitorName, row.CompanyName, row.VisitsCount, row.LatestVisit, row.Status] : [row.VisitorName, row.CompanyName, row.InductionVersion, row.CompletedAt, row.ValidUntil, row.Status];
  return <Layout><h1 className="text-xl font-bold mb-5">Laporan Operasional</h1><div className="report-tabs" role="tablist">{(['visits', 'visitors', 'inductions'] as Tab[]).map(item => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => switchTab(item)}>{item === 'visits' ? 'Kunjungan' : item === 'visitors' ? 'Pengunjung' : 'Safety Induction'}</button>)}</div>{filters}{error ? <ErrorState message={error} onRetry={load} /> : loading ? <p>Memuat laporan...</p> : !rows.length ? <EmptyState message="Belum ada data laporan." /> : <><div className="overflow-x-auto bg-white border rounded report-table"><table className="w-full text-sm"><thead><tr>{csvHeaders[tab].map(header => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{values(row).map((value, cell) => <td key={cell}>{value == null ? '-' : String(value)}</td>)}</tr>)}</tbody></table></div><div className="mobile-record-list">{rows.map((row, index) => <article key={index} className="mobile-record-card"><strong>{String(values(row)[0] ?? '-')}</strong><dl className="mobile-record-details">{csvHeaders[tab].slice(1).map((header, cell) => <div key={header}><dt>{header}</dt><dd>{String(values(row)[cell + 1] ?? '-')}</dd></div>)}</dl></article>)}</div><div className="flex gap-3 mt-4"><button disabled={page <= 1} onClick={() => setPage(value => value - 1)} className="px-3 py-1 border rounded disabled:opacity-40">Sebelumnya</button><span className="py-1 text-sm">Halaman {page} dari {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage(value => value + 1)} className="px-3 py-1 border rounded disabled:opacity-40">Berikutnya</button></div></>}</Layout>;
}
