import { useEffect, useState } from 'react';
import { Layout } from '../components/Layout';
import { DevFillButton } from '../components/DevFillButton';
import { deleteInductionContent, listManagedInductionContents, updateInductionContentStatus, uploadInductionContent } from '../api/safety-inductions.api';
import { type InductionContent } from '../types/induction';
import { confirmAction } from '../components/ConfirmationHost';
import { ErrorState, EmptyState } from '../components/AsyncState';
import { useLanguage } from '../i18n/LanguageContext';
import { userFacingError } from '../api/client';

export function SafetyInductionManagementPage() {
  const { language, t } = useLanguage(); const [contents, setContents] = useState<InductionContent[]>([]); const [file, setFile] = useState<File | null>(null); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [actionId, setActionId] = useState<number | null>(null);
  useEffect(() => { void load(); }, []);
  async function load() { setLoading(true); setError(''); try { setContents(await listManagedInductionContents()); } catch (cause) { setError(userFacingError(cause, language)); } finally { setLoading(false); } }
  async function handleUpload(event: React.FormEvent) { event.preventDefault(); if (!file || saving) return; setSaving(true); setError(''); try { await uploadInductionContent({ file, title, description }); setFile(null); setTitle(''); setDescription(''); const input = document.getElementById('content-file') as HTMLInputElement | null; if (input) input.value = ''; await load(); } catch (cause) { setError(userFacingError(cause, language)); } finally { setSaving(false); } }
  async function handleToggle(content: InductionContent) { if (actionId !== null) return; setActionId(content.Id); setError(''); try { await updateInductionContentStatus(content.Id, !content.IsActive); await load(); } catch (cause) { setError(userFacingError(cause, language)); } finally { setActionId(null); } }
  async function handleDelete(content: InductionContent) { const name = content.Title || content.ContentUrl; if (!await confirmAction(`${t('safetyContent.deleteConfirm')}\n"${name}" ${t('safetyContent.deleteWarning')}`)) return; setActionId(content.Id); setError(''); try { await deleteInductionContent(content.Id); await load(); } catch (cause) { setError(userFacingError(cause, language)); } finally { setActionId(null); } }
  const contentType = (type: InductionContent['ContentType']) => type === 'VIDEO' ? t('safetyContent.video') : type === 'IMAGE' ? t('safetyContent.image') : t('safetyContent.pdf');
  return <Layout><div className="safety-content-page"><header className="page-header-compact"><div><p className="page-eyebrow">{t('safetyContent.eyebrow')}</p><h1>{t('safetyContent.title')}</h1><p>{t('safetyContent.description')}</p></div><DevFillButton onClick={() => { setTitle(t('safetyContent.sampleTitle')); setDescription(t('safetyContent.sampleDescription')); }} label={t('safetyContent.sample')} /></header>
    {error && <ErrorState message={error} onRetry={load} />}
    <form onSubmit={handleUpload} className="safety-upload-form"><h2>{t('safetyContent.upload')}</h2><div className="safety-upload-grid"><div className="file-picker-field"><span className="form-field-label">{t('safetyContent.file')}</span><label htmlFor="content-file" className="file-picker-button">{t('safetyContent.chooseFile')}</label><input id="content-file" type="file" onChange={event => setFile(event.target.files?.[0] || null)} required disabled={saving} /><span className="selected-file" aria-live="polite">{file?.name || t('safetyContent.noFile')}</span></div><div><label htmlFor="content-title" className="form-field-label">{t('safetyContent.titleLabel')}</label><input id="content-title" value={title} onChange={event => setTitle(event.target.value)} disabled={saving} /></div><div><label htmlFor="content-description" className="form-field-label">{t('safetyContent.descriptionLabel')} ({t('safetyContent.optional')})</label><textarea id="content-description" value={description} onChange={event => setDescription(event.target.value)} rows={2} disabled={saving} /></div></div><button type="submit" disabled={!file || saving} className="primary-button">{saving ? t('safetyContent.uploading') : t('safetyContent.uploadButton')}</button><p className="form-helper">{t('safetyContent.helper')}</p></form>
    {loading ? <p className="page-loading" role="status">{t('safetyContent.loading')}</p> : contents.length === 0 ? <EmptyState message={t('safetyContent.noContent')} /> : <div className="safety-content-list">{contents.map(content => <article key={content.Id} className="safety-content-card"><div className="safety-content-heading"><div><h2>{content.Title || content.ContentUrl}</h2><div className="safety-content-tags"><span className="content-type-badge">{contentType(content.ContentType)}</span><span className={`status-badge ${content.IsActive ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-700'}`}>{content.IsActive ? t('safetyContent.visible') : t('safetyContent.hidden')}</span></div></div><div className="safety-content-actions"><button type="button" className="secondary-button" disabled={actionId === content.Id} onClick={() => void handleToggle(content)}>{content.IsActive ? t('safetyContent.hide') : t('safetyContent.show')}</button><button type="button" className="danger-button" disabled={actionId === content.Id} onClick={() => void handleDelete(content)}>{t('common.delete')}</button></div></div>{content.Description && <p className="safety-content-description">{content.Description}</p>}</article>)}</div>}
  </div></Layout>;
}
